using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public enum UpgradeType {

	BASIC_TOWER_DAMAGE,
	BASIC_TOWER_ATTACKSPEED,
	BASIC_TOWER_RANGE,
	SPLASH_TOWER_DAMAGE,
	SPLASH_TOWER_ATTACKSPEED,
	SPLASH_TOWER_RANGE,
	ANTIAIR_TOWER_DAMAGE,
	ANTIAIR_TOWER_ATTACKSPEED,
	ANTIAIR_TOWER_RANGE,
	DRAGON_DAMAGE_AURA,
	DRAGON_ATTACKSPEED_AURA,
	DRAGON_RANGE_AURA,
	DRAGON_NO_AURA
}
